### PR TITLE
Evaluation

### PR DESCRIPTION
**Pull request by Geet-George**
This PR will add information about the evaluation for the Python part of the course. It is intended to give an idea to the students about what is expected from the project.

### CODE REVIEW

**Comment by Geet-George** [comment]
@yustisiardhitasari @owenodriscoll @khaakman let me know if you have any suggestions for the evaluation guidelines. I will be adding it to the webpage to make the students aware of what they should focus their efforts on. If you think something is missing or if something sounds weird (cannot be tested, difficult to achieve, etc.), let me know.

This page should be built and deployed at https://geet-george.github.io/test-doc-pack/evaluation and the page being discussed is here: https://geet-george.github.io/test-doc-pack/evaluation/content/course/evaluation.html

**Comment by Geet-George** [comment]
I'm assuming no comments here and merging this.

**Comment by owenodriscoll** [comment]
Hi @Geet-George (and @khaakman @yustisiardhitasari), I agree with the evaluation guidelines and I'm very much in favour of the students including screenshots rather than us having to run their code.

Perhaps to make grading more clear/transparant, we can come up with one more assessment category for a total of nine, giving 1 point per category plus 1 base point. 

Then we could do something along the lines of: 1 point per category, subtracting 0.25 per deficiency, up to -0.75. The maximum penalty for non-functioning code would be quite limited and in the student's favour.  For instance:
Readme included --> + 1
Readme content outdated for repository structure --> -0.25
Python functions present --> +1 
not all functions work --> -0.25
wrong function structure --> -0.25
poor syntax --> -0.25

For the ninth category I was thinking something along the lines of the submission itself. Students could open an issue on their repository and assign us. Their they could add comments and screenshots that do not belong in the readme, such as related to their tests and or explanations of aspects that do not work

**Comment by Geet-George** [comment]
I like the ninth category of assessing the submission itself. The rest is very similar to how I have actually done the evaluation. But nice ideas, thanks :)

**Pull request merged**
